;;; evil-textobj-line-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from evil-textobj-line.el

(register-definition-prefixes "evil-textobj-line" '("evil-"))

;;; End of scraped data

(provide 'evil-textobj-line-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; evil-textobj-line-autoloads.el ends here
